### ISSUE TITLE
# seqs in tree file does not match.  Read as the nexus format.

### ISSUE THREAD

**Issue by RetroWWU** [abacus-gene/paml#30]
Codeml from PAML 4.10.6 is not correctly processing the site models. Using our or your GitHub examples always lead to the same error: "# seqs in tree file does not match. Read as the nexus format."  This error is also reproduced using codeml from PAML 4.10.3. However, the same data sets were used in the codeml from 4.10.0. or older leads to correct processing.
Please fix this PAML 4.10 issue. 
Best regards, Juergen Schmitz

[AZI2_fasta.txt](https://github.com/abacus-gene/paml/files/11834310/AZI2_fasta.txt)
[AZI2_tree.txt](https://github.com/abacus-gene/paml/files/11834316/AZI2_tree.txt)
[codeml_ctl.txt](https://github.com/abacus-gene/paml/files/11834318/codeml_ctl.txt)

**Comment by sabifo4** [comment]
Hi there,

Thanks for reporting this issue! Some days ago, I downloaded your dataset and ran some tests with the [`paml-4.10.6`](https://github.com/abacus-gene/paml/releases/tag/v4.10.6) release -- note that I had to change the name of the alignment file you pass to option `seqfile` as it did not match the name you had given to your input alignment file (i.e., you had `seqfile = AZI2_U.fasta.txt` while your file name is `AZI2_fasta.txt`).

To make it easier to debug, I changed the extension of the file names so that the alignment file is `AZI2.fasta` and the tree file is `AZI2.tree`. Note that, however, we recommend using an alignment in PHYLIP format in case issues with the FASTA format occur.

I tested the following:

1. Your input data + compiled source code after cloning the current GitHub repository.
2. Your input data + compiled source code from release 4.10.6 (Linux and Windows pre-compiled binaries).
3. Your input data + compiled source code from release 4.10.6 (compressed files).

The first two tests were successful, but the last one was not: I could reproduce the problem you mention as I got the same error. The source code available as part of the release that was labelled as "latest" when you reported this issue ([`paml-4.10.6`](https://github.com/abacus-gene/paml/releases/tag/v4.10.6)) did not include the latest version of the code that you would use if cloning the repository or downloading the pre-compiled binaries. A new release is now available for download where this bug is fixed: [`paml-4.10.7`](https://github.com/abacus-gene/paml/releases/tag/4.10.7). 

I will close this issue as it is now resolved, thanks again for letting us know!
