### ISSUE TITLE
 Error: you should specify # seqs in the tree file.

### ISSUE THREAD

**Issue by myoucchent** [abacus-gene/paml#37]
Hi, there is an error when I run the mcmctree, counld you give me some help?
 this is my tree:
((Dicentrarchus_labrax,(Larimichthys_crocea,(Acanthopagrus_latus,Sparus_aurata)))'>2.1',((Epinephelus_lanceolatus,Sander_lucioperca#),(Lates_calcarifer,(Oreochromis_niloticus,(Danio_rerio,(Oryzias_latipes,Oryzias_melastigma))))),(Lateolabrax_maculatus,Micropterus_salmoides));

this is error log:
 mcmctree mcmctree3.ctl
MCMCTREE in paml version 4.10.0, September 2020

Reading options from mcmctree3.ctl..
finetune is deprecated now.
Reading master tree.

Error: you should specify # seqs in the tree file.

**Comment by sabifo4** [comment]
Hi there!

You may need to add the PHYLIP header in the tree file. As you have 13 tag IDs, then your tree file should have the following:

```
13  1
((Dicentrarchus_labrax,(Larimichthys_crocea,(Acanthopagrus_latus,Sparus_aurata)))'>2.1',((Epinephelus_lanceolatus,Sander_lucioperca#),(Lates_calcarifer,(Oreochromis_niloticus,(Danio_rerio,(Oryzias_latipes,Oryzias_melastigma))))),(Lateolabrax_maculatus,Micropterus_salmoides));
```

You may want to check [the section on the PAML Wiki with regards to data formatting ](https://github.com/abacus-gene/paml/wiki/Data-formatting) to make sure your input files are correctly formatted.

Please let me know if that sorted out your issue so that I can close it.

Hope this helps!

**Comment by myoucchent** [comment]
thank you very much! I select a branch as root seq in my tree. I have solved this problem.
