### ISSUE TITLE
error for run: codeml codem.ctl  

### ISSUE THREAD

**Issue by panpanchen123** [abacus-gene/paml#39]
Hello, when I run codeml codeml.ctl ,it shows
 ns = 7  	ls = 1643893
Reading sequences, sequential format..
Reading seq # 1: Arur       
Reading seq # 2: Daca       
Reading seq # 3: Dape       
Reading seq # 4: Lesa       

Error: EOF?.

 Please tell me how should I solve this problem，thank you very much.

**Comment by sabifo4** [comment]
Hi there,

This error message is letting you know that CODEML has reached the end of the sequence file and there are no more sequences to be read (i.e., you specified that you have 7 sequences in the PHYLIP header, but it seems you only have four, according to your message). Without the input files and the control files, it is hard to troubleshoot what may have gone wrong, however.

Please note that this is just an error message letting you know that there is a problem with your input data, not a technical problem with the program itself. In addition, this question has been asked several times on the PAML Google Group, e.g., [latest thread](https://groups.google.com/g/pamlsoftware/c/zlRJTj3abmA/m/iKQkW87xBAAJ). Most of the times, these questions have been asked before in the PAML Google Group, so you may want to first check if that's the case to avoid having duplicates of the same question that has already been resolved :)

Hope this helps!

**Comment by jiajia-a11y** [comment]
Hello, when I run codeml codeml.ctl ,it shows:
Counting frequencies..
635756 patterns, messy
*** Locus 1 ***
running codeml tmp0001.ctl

Error: model unavailable.
file rst2 not found!
Please tell me how should I solve this problem, thank you very much.

**Comment by sabifo4** [comment]
Hi there,

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki) and in the main [README.md file](https://github.com/abacus-gene/), the issues to be raised in the GitHub repository are to be related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this issue should have been posted on the PAML discussion group, please find below some guidelines that I hope answer your question.

I may be wrong, but it looks as if you used the wrong evolutionary model when trying to run MCMCtree when using `usedata = 3`, and thus `CODEML` inherited the wrong settings. To further troubleshoot this problem, I will need the input files and the control file you are using. Could you please post a message with this information and your input files on the [PAML discussion group](https://groups.google.com/g/pamlsoftware)? To this end, the PAML community will also benefit from any discussions and solutions the PAML community has to suggest.

Thank you!

**Comment by sabifo4** [comment]
Hi there,

Could you please attach your input files and control file so that we can troubleshoot what may be going on? We never received such files from the user who first reported this screen output on this issue, and thus I could only hypothesise that the issues could have beene related to some settings specified in the control file (e.g., "usedata"), but never tested that. 

Another user reported this screen message on [the PAML discussion group](https://groups.google.com/g/pamlsoftware/c/BDp8NKduVvI/m/FJ8g2krlCQAJ), which ended up being related to the sequence alignment format -- they had used an interleaved format that was not ideal. If that is your case, I suggest you create an input sequence file with one sequence per line. E.g.: assuming that `n_taxa` is the number of taxa in your alignment, `n_sites` the number of characters in your alignment, `sp_X` the tags to identify your sequences, your sequence alignment should look like the following if having one sequence per line (I am ussing `[...]` to indicate that the sequences continue and that there may be other sequences between `sp_2` and `sp_n`):

```text
n_taxa n_sites
sp_1     AACCATAG [...]
sp_2     AACCATCG [...]

[...]

sp_n     AACATTGA [...]
```

If this does not resolve your issue, please attach your input files and control file so that we can test further. Thanks in advance!
