### ISSUE TITLE
 mcmctree terminated with errors "resetting lnL" when usedata =2

### ISSUE THREAD

**Issue by yemingyue222** [abacus-gene/paml#44]
Hello, I meet a problem when using approximate likelihood calculation during the MCMC. Please help me.

My phylogenetic tree is over 100 taxa, I want to shorten the estimation of divergence time, so I use approximate likelihood calculation. The first step "usedata = 3" is smooth, but the next step "usedata = 2"in nohup.out file, e.g., 910275614542723227185095639040.000000 = 910275614542725760459886034944.000000? Resetting lnL 
Similar sentences appear five times. Please check my compressed files including 4 input files (input.tre
[input.tre.zip](https://github.com/abacus-gene/paml/files/14571744/input.tre.zip)
, input.phy
[input.phy.zip](https://github.com/abacus-gene/paml/files/14571723/input.phy.zip)
, mcmctree2.ctl
[mcmctree2.ctl.zip](https://github.com/abacus-gene/paml/files/14571746/mcmctree2.ctl.zip)
, in.BV) and 4 output files [output files.zip](https://github.com/abacus-gene/paml/files/14571689/output.files.zip) (nohup.out, mcmc.out, mcmc.txt, SeedUsed), I would sincerely appreciate your advice.

Look forward to your reply!
Best regards, 

Mingyue YE

**Comment by sabifo4** [comment]
Hi there!

Thanks for your message, but please note that [there is a PAML discussion group](https://groups.google.com/g/pamlsoftware) where this type of questions should be posted as then all users can benefit from the answers given by the PAML community :)

I have checked your input files and I can see that you do not have a constrain in your root age in your tree file. Instead, you just added option `RootAge` in the control file specifying an upper bound of max. 1.0 (time unit), which is currently deprecated. I just wanted to check that this was indeed the constrain you wanted to apply for your root age. Option `finetune` is deprecated, so there is no need to include it in the control file. 

As I cannot see the `in.BV` file, I cannot really troubleshoot what may have gone wrong there. Regarding the format of this file, you should make sure that there are as many blocks with branch lengths, gradient, and Hessian in the `in.BV` file as alignment blocks you have in your alignment file (i.e., 353 according to variable `ndata` in your control file). They also should be in the same order as the alignment blocks in your alignment file (first block with branch lengths, gradient, and Hessian in the `in.BV` file should correspond to the first alignment block in your alignment file, etc.). Can you confirm that the `in.BV` follows this format? 

Please post a message in the [PAML discussion group](https://groups.google.com/g/pamlsoftware) and attach a compressed file with the `in.BV` file, control file, alignment file, and input file that you are using to continue troubleshooting this issue -- please let us know whether there was an issue with the `in.BV` file you were using or whether the issue still persists after making sure the format is correct.

I will close this issue here as it is not a technical problem related to MCMCtree. Nevertheless, I shall reopen this issue if a technical problem is later found :)
