### ISSUE TITLE
Same lnLs in Model A and corresponding null model of the Branch-Site models

### ISSUE THREAD

**Issue by Jinloong-dream** [abacus-gene/paml#49]
hi, guys!
I'm in trouble with codeml for **positve selection**
Model A:
![image](https://github.com/abacus-gene/paml/assets/172971324/fd78b9e4-4e18-45e7-8ab2-b544507ef7e9)
![image](https://github.com/abacus-gene/paml/assets/172971324/8cb827d8-ed18-4cd1-a292-78757750d330)
Null model:
![image](https://github.com/abacus-gene/paml/assets/172971324/c6851315-5958-41cc-a4d4-43d2e194e0e4)
![image](https://github.com/abacus-gene/paml/assets/172971324/c168dbf0-c507-46c6-851f-4a802221186a)
But the results of both are always the same
![image](https://github.com/abacus-gene/paml/assets/172971324/4f7abf5d-25e9-49a4-a865-99a604c8aeaf)
crazy!

Thanks, 
Jinloong

**Comment by sabifo4** [comment]
Hi there!

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki), the GitHub repository is aimed at issues related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this issue should have been posted on the PAML discussion group, please find below some guidelines to answer your question.

Without the input files or the control file, it is very hard to troubleshoot this issue. Could you please post this issue on the [PAML discussion group](https://groups.google.com/g/pamlsoftware) and attach your input files so that the PAML community can assist you further?  :)

All the best,
Sandy
