### ISSUE TITLE
pairwise model require tree file now?

### ISSUE THREAD

**Issue by dukecomeback** [abacus-gene/paml#53]
I was using runmode=-2 in codeml.ctl, it returned error "tree file  not found."

**Comment by sabifo4** [comment]
Hi there,

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki), the GitHub repository is aimed at issues related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this issue should have been posted on the PAML discussion group, please find below some guidelines to answer your question.

To answer your questions, however, we need to be able to reproduce the error you are getting, and so we need the input files and control file you are using. I believe it may be due to issues with the format of your input files, and so I recommend you check those in [the `Data formatting` section in the PAML Wiki](https://github.com/abacus-gene/paml/wiki/Data-formatting). If you still find the same error, please ask your question in the [PAML discussion group](https://groups.google.com/g/pamlsoftware) and attach your input and control files so that we can troubleshoot this issue.

Thank you!
