### ISSUE TITLE
maintree file can have only one tree

### ISSUE THREAD

**Issue by louisfnastasi** [abacus-gene/paml#54]
Hi PAML team,

I have a brief question regarding the following error while attempting to run mcmctree: maintree file can have only one tree

My treefile definitely contains only a single tree, and I believe my calibration points are properly formatted according to the documentation.

My tree and control file are attached, combined into a single pdf as the original file types are not supported.
[mcmctree_issue.pdf](https://github.com/user-attachments/files/17577334/mcmctree_issue.pdf)

Thanks in advance!

**Comment by sabifo4** [comment]
Hi there,

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki), the GitHub repository is aimed at issues related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this issue should have been posted on the PAML discussion group, please find below some guidelines to answer your question.

I suspect you are missing the PHYLIP header in your tree file as specified in [the Data formatting section in the PAML Wiki](https://github.com/abacus-gene/paml/wiki/Data-formatting#tree-file-format-and-representations-of-tree-topology). In addition, I have seen you still have option `RootAge` in the control file, but we recommend to add the root age constraint directly in the calibrated tree file (i.e., at the end of the Newick tree topology; `Sparasion_cullaris_1322137))) '>1.82<2.237';`) and remove the option from the control file. Regarding other options in the control file, you may want to add option `seqtype` to specify the type of data you have (i.e., 0: nucleotides; 1:codons; 2:AAs). In addition, I think the sampling frequency is too low, but it may work with your dataset -- just check the traces and convergence plots during the MCMC diagnostics to check your chains are healthy! Lastly, I see that you have commented option `mcmcfile`, and so you will not generate an output file with the samples collected during the MCMC -- you should uncomment this :)

If you still find the same error or other errors when using MCMCtree, please ask your question in the [PAML discussion group](https://groups.google.com/g/pamlsoftware) and attach your input and control files so that we can troubleshoot this issue :)

Thank you!
