### ISSUE TITLE
How to obtain an unrooted tree from a rooted tree?

### ISSUE THREAD

**Issue by Tangbbmc** [abacus-gene/paml#55]
I constructed a ML tree with iq-tree software. When testing site-models (NSsites = 0 1 2 7 8 ) with PAML, this program issued a warning message "This is a rooted tree. Please check!" Then, how to obtain an rooted tree from the current rooted tree created by iq-tree? Thank you!

**Comment by sabifo4** [comment]
Hi there,

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki) and in the main [README.md file](https://github.com/abacus-gene/), the issues to be raised in the GitHub repository are to be related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this issue is not really related to PAML, please find below some guidelines to answer your question.

Phylogenetic software tend to output unrooted trees unless the user specifies an outgroup to root it. When you obtain an unrooted tree, you can either manually root the Newick-formatted tree using your favourite text editor or using one of the many graphical interfaces out there (e.g., [TreeViewer](https://treeviewer.org/), [FigTree](http://tree.bio.ed.ac.uk/software/figtree/), etc.). Once you root your tree, you can save it in the most convenient format for subsequent phylogenetic analyses. For PAML analyses, you should save it in Newick format. In addition, please remember to remove the branch lengths if you are to use them when running CODEML and add a PHYLIP header as explained in our ["Beginner's guide on the use of PAML to detect positive selection" (Álvarez-Carretero et al., 2023](https://academic.oup.com/mbe/article/40/4/msad041/7140562?login=false) and in [our PAML Wiki](https://github.com/abacus-gene/paml/wiki/Data-formatting#tree-file-format-and-representations-of-tree-topology).

Thank you!
