### ISSUE TITLE
Error: end of tree file..

### ISSUE THREAD

**Issue by Tangbbmc** [abacus-gene/paml#56]
[tree.zip](https://github.com/user-attachments/files/17609124/tree.zip)

When testing site-models with PAML, the terminal window issued a message "Error: end of tree file.."  I have uploaded the tree file.

**Comment by sabifo4** [comment]
Hi there,

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki) and in the main [README.md file](https://github.com/abacus-gene/), the issues to be raised in the GitHub repository are to be related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). While this issue should have been posted on the PAML discussion group, please find below some guidelines to answer your question.

I can see that your tree file is missing the PHYLIP header and you need to remove the branch lengths as specified in [the Data formatting section in the PAML Wiki](https://github.com/abacus-gene/paml/wiki/Data-formatting#tree-file-format-and-representations-of-tree-topology). I suggest you read our ["Beginner's guide on the use of PAML to detect positive selection" (Álvarez-Carretero et al., 2023](https://academic.oup.com/mbe/article/40/4/msad041/7140562?login=false) , which includes all the details you need to know to run CODEML to test for positive selection. The analyses detailed in the protocol can be reproduced if you [follow the step-by-step tutorial in our GitHub repository `positive-selection`](https://github.com/abacus-gene/paml-tutorial/tree/main/positive-selection) -- you have template scripts and the input/output files described in the protocol.

If you still find the same error or other errors when using CODEML, please ask your question in the [PAML discussion group](https://groups.google.com/g/pamlsoftware) and attach your input and control files so that we can troubleshoot this issue :)

Thank you!
