### ISSUE TITLE
Why a fully conserved site was identified as a positive selection site?

### ISSUE THREAD

**Issue by Tangbbmc** [abacus-gene/paml#57]
I used the branch-site model (model 2, NSsites = 2) to identify the positive selection site with PAML. It is very strange that a fully conserved Ser residue in both foreground and background lineages was identified as a positive selection site (Bayes Empirical Bayes possibility>0.99). Is this possible? I am looking forward to your reply as soon as possible!

**Comment by sabifo4** [comment]
Hi there,

As explained in [the PAML Wiki](https://github.com/abacus-gene/paml/wiki) and in the main [README.md file](https://github.com/abacus-gene/), the issues to be raised in the GitHub repository are to be related to technical issues. For non-technical questions and debates, there is a [PAML discussion group](https://groups.google.com/g/pamlsoftware) that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question). 

Could you please post this question in the [PAML discussion group](https://groups.google.com/g/pamlsoftware) as other users may find it relevant? In addition, you may get different answers/perspectives from different PAML users. In addition, if you want to verify that there were no issues when you ran your program and/or you did not misidentify the foreground and background branches, please attach your input sequence and tree files, as well as the control file, so that we can troubleshoot.

Thank you!

**Comment by Tangbbmc** [comment]
Unfortunately, I cannot open the website of PAML discussion group


---- Replied Message ----
From  Sandra ***@***.***> Date  11/04/2024 19:22 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [abacus-gene/paml] Why a fully conserved site was identified as a positive selection site? (Issue #57)  

Hi there,
As explained in the PAML Wiki and in the main README.md file, the issues to be raised in the GitHub repository are to be related to technical issues. For non-technical questions and debates, there is a PAML discussion group that people are encouraged to use -- you may even find that similar questions to yours have been posted there (e.g., use the search bar and use key words to find the answer to your question).
Could you please post this question in the PAML discussion group as other users may find it relevant? In addition, you may get different answers/perspectives from different PAML users. In addition, if you want to verify that there were no issues when you ran your program and/or you did not misidentify the foreground and background branches, please attach your input sequence and tree files, as well as the control file, so that we can troubleshoot.
Thank you!

**Comment by sabifo4** [comment]
You should be able to copy and paste the following URL on your web browse: https://groups.google.com/g/pamlsoftware

**Comment by Tangbbmc** [comment]
Sorry. I still fail to open the website you provided! Maybe, it has limitation for Chinese users.

发件人：Sandra AC ***@***.***>
发送日期：2024-11-04 19:55:40
收件人：abacus-gene/paml ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [abacus-gene/paml] Why a fully conserved site was identified as a positive selection site? (Issue #57)

You should be able to copy and paste the following URL on your web browser: https://groups.google.com/g/pamlsoftware

**Comment by sabifo4** [comment]
I see, that is a shame -- it is a great group where you can explore various discussions on the usage of PAML and ask your own questions to the whole community :)

Can you please attach your input sequence and tree files and your control file in your next message so that we can troubleshoot the analysis you carried out?

Thanks you!

**Comment by Tangbbmc** [comment]
OK! Many thanks for kind help! I have attached all files (tree file, sequence file, control file, and output file) as a compressed format. A fully conserved Ser307 was also identified as a positive selection site using branch-site model. I am looking forward to your reply as soon as possible!
[PAML_TWG.zip](https://github.com/user-attachments/files/17618512/PAML_TWG.zip)

**Comment by sabifo4** [comment]
Hi again,

I have now had time to go through your files! The most important thing for you to do first is to get a bit more familiar with the PAML documentation, and so I suggest you go through the [PAML Wiki](https://github.com/abacus-gene/paml/wiki) to understand which formats are required to run PAML programs, how PAML programs are run, etc.

To better understand how to run CODEML to test for positive selection, which is what I think you are trying to do after checking your input files, you should first read our latest protocol: [Beginner's Guide on the Use of PAML to Detect Positive Selection (Álvarez-Carretero et al., 2023)](https://academic.oup.com/mbe/article/40/4/msad041/7140562). You can find the example data that we use in the protocol in [our GitHub repository `positive-selection`](https://github.com/abacus-gene/paml-tutorial/tree/main/positive-selection). You have all the steps from the data collection until CODEML analyses in the [`00_data` directory](https://github.com/abacus-gene/paml-tutorial/tree/main/positive-selection/00_data), and plenty of examples to run various models implemented in CODEML to test for positive selection in directory [`01_protocol_analyses`](https://github.com/abacus-gene/paml-tutorial/tree/main/positive-selection/01_protocol_analyses). If you follow all the `README.md` files from directory `00_data`, you will be able to navigate the whole GitHub repository!

When going through your files, I saw that your tree file did not have the correct format: you missed your PHYLIP header and you had to remove the branch lengths. I assume that you have properly filtered and aligned your sequence alignment (we give suggestions in our paper and in our repository mentioned above) but, if not, please check. 

With regards to your control file, please note that there you have included lots of unused options for the analysis you want to run, and some of them were even repeated -- please check the tutorial aforementioned as well as the example control files provided in the GitHub repository cited above for more information. Also, please make sure that you are using the correct code. In other words, you have set option `icode = 0` in your control file, but you have uracil in your sequences, so I am not sure which code you are supposed to use as I do not know which sequences you have. Please check your sequences and select the correct code using the options below, which are also explained in the PAML documentation:

* 0: universal,
* 1: mammalian mt.
* 2: yeast mt.
* 3: mold mt.
* 4: invertebrate mt.
* 5: ciliate nuclear
* 6: echinoderm mt.
* 7: euplotid mt.
* 8: alternative yeast nu.
* 9: ascidian mt.
* 10: blepharisma nu.

> **NOTE** These codes correspond to `transl_table` 1 to 11 of GENEBANK.

Lastly, please check which codon frequencies you want to use (e.g., how to specify options `estFreq` and `CodonFreq` in the control file), which you can find in the [PAML documentation](https://github.com/abacus-gene/paml/blob/master/doc/pamlDOC.pdf) under the `CODEML` section and it is also described in our protocol paper. The tests I ran used the following control file, but you may need to update some of the settings so that they fit your dataset:

```
      seqfile = GENE.pml * sequence data filename
     treefile = tree.txt     * tree structure file name
      outfile = out.txt           * main result file name

        noisy = 9  * 0,1,2,3,9: how much rubbish on the screen
      verbose = 1  * 0: concise; 1: detailed, 2: too much

      seqtype = 1  * 1:codons; 2:AAs; 3:codons-->AAs
        ndata = 1  * Number of datasets or loci
        icode = 0  * 0:universal code; 1:mammalian mt; 2-10:see below
    cleandata = 0  * Remove sites with ambiguity data?

        model = 2  * Models for ω varying across lineages
	  NSsites = 2  * Models for ω varying across sites
    CodonFreq = 7  * Codon frequencies
      estFreq = 0        * Use observed freqs or estimate freqs by ML
        clock = 0          * Clock model
    fix_omega = 0         * Estimate or fix omega
        omega = 0.5        * Initial or fixed omega
```

When re-running your analyses, I found only 4 sites that are potentially under positive selection under the branch-site model, which are different from the sites you found except for the sites in position 45. Based on what these sequences are (i.e., which protein coding gene are you using?), you may be able to better understand where these AAs are in the sequence and whether they may have key roles in the protein itself (e.g., folding, function, etc.). You may have a specific biological hypothesis that are testing at the moment, and so the findings with the branch-site model may help you understand better what is going on. It is now your turn to gather more insights into how to interpret such results based on the taxa you have in your phylogeny and the data you have used!

P.S.: while we provide users with recommendations and suggestions about how to run PAML programs and address their questions regarding technical issues, it is out of the scope of our tasks to run the programs on behalf of users and fully interpret their results -- they are the ones who are using phylogenetic software to test a biological hypothesis with their data to gain new insights in such hypothesis. To this end, users are responsible to go through the documentation, get familiar with the programs they want to use, run them to test their hypotheses, and interpret their results -- we can help clarify doubts, but not run the full analysis; hope this makes sense! The PAML documentation is very detailed and we have a PAML Wiki, plenty of tutorials and data examples that people can go through, and protocol papers with GitHub repositories that can be used to reproduce the steps detailed in such protocols -- I highly suggest you go through those! :)

**Comment by Tangbbmc** [comment]
I deeply appreciated for your patient response and usefull suggestion! I will carefully learn the PAML documentation and other protocols you recommended. Best regards!

From: Sandra AC ***@***.***>
Date: 2024-11-09 00:46:57
To: abacus-gene/paml ***@***.***>
Cc: Wanggang ***@***.***>,Author ***@***.***>
Subject: Re: [abacus-gene/paml] Why a fully conserved site was identified as a positive selection site? (Issue #57)

Hi again,
I have now had time to go through your files! The most important thing for you to do first is to get a bit more familiar with the PAML documentation, and so I suggest you go through the PAML Wiki to understand which formats are required to run PAML programs, how PAML programs are run, etc.
To better understand how to run CODEML to test for positive selection, which is what I think you are trying to do after checking your input files, you should first read our latest protocol: Beginner's Guide on the Use of PAML to Detect Positive Selection (Álvarez-Carretero et al., 2023). You can find the example data that we use in the protocol in our GitHub repository positive-selection. You have all the steps from the data collection until CODEML analyses in the 00_data directory, and plenty of examples to run various models implemented in CODEML to test for positive selection in directory 01_protocol_analyses. If you follow all the README.md files from directory 00_data, you will be able to navigate the whole GitHub repository!
When going through your files, I saw that your tree file did not have the correct format: you missed your PHYLIP header and you had to remove the branch lengths. I assume that you have properly filtered and aligned your sequence alignment (we give suggestions in our paper and in our repository mentioned above) but, if not, please check.
With regards to your control file, please note that there you have included lots of unused options for the analysis you want to run, and some of them were even repeated -- please check the tutorial aforementioned as well as the example control files provided in the GitHub repository cited above for more information. Also, please make sure that you are using the correct code. In other words, you have set option icode = 0 in your control file, but you have uracil in your sequences, so I am not sure which code you are supposed to use as I do not know which sequences you have. Please check your sequences and select the correct code using the options below, which are also explained in the PAML documentation:
0: universal, 1: mammalian mt. 2: yeast mt. 3: mold mt. 4: invertebrate mt. 5: ciliate nuclear 6: echinoderm mt. 7: euplotid mt. 8: alternative yeast nu. 9: ascidian mt. 10: blepharisma nu.NOTE These codes correspond to transl_table 1 to 11 of GENEBANK.
Lastly, please check which codon frequencies you want to use (e.g., how to specify options estFreq and CodonFreq in the control file), which you can find in the PAML documentation under the CODEML section and it is also described in our protocol paper. The tests I ran used the following control file, but you may need to update some of the settings so that they fit your dataset:
      seqfile = GENE.pml * sequence data filename
     treefile = tree.txt     * tree structure file name
      outfile = out.txt           * main result file name

        noisy = 9  * 0,1,2,3,9: how much rubbish on the screen
      verbose = 1  * 0: concise; 1: detailed, 2: too much

      seqtype = 1  * 1:codons; 2:AAs; 3:codons-->AAs
        ndata = 1  * Number of datasets or loci
        icode = 0  * 0:universal code; 1:mammalian mt; 2-10:see below
    cleandata = 0  * Remove sites with ambiguity data?

        model = 2  * Models for ω varying across lineages
	  NSsites = 2  * Models for ω varying across sites
    CodonFreq = 7  * Codon frequencies
      estFreq = 0        * Use observed freqs or estimate freqs by ML
        clock = 0          * Clock model
    fix_omega = 0         * Estimate or fix omega
        omega = 0.5        * Initial or fixed omega
When re-running your analyses, I found only 4 sites that are potentially under positive selection under the branch-site model, which are different from the sites you found except for the sites in position 45. Based on what these sequences are (i.e., which protein coding gene are you using?), you may be able to better understand where these AAs are in the sequence and whether they may have key roles in the protein itself (e.g., folding, function, etc.). You may have a specific biological hypothesis that are testing at the moment, and so the findings with the branch-site model may help you understand better what is going on. It is now your turn to gather more insights into how to interpret such results based on the taxa you have in your phylogeny and the data you have used!
P.S.: while we provide users with recommendations and suggestions about how to run PAML programs and address their questions regarding technical issues, it is out of the scope of our tasks to run the programs on behalf of users and fully interpret their results -- they are the ones who are using phylogenetic software to test a biological hypothesis with their data to gain new insights in such hypothesis. To this end, users are responsible to go through the documentation, get familiar with the programs they want to use, run them to test their hypotheses, and interpret their results -- we can help clarify doubts, but not run the full analysis; hope this makes sense! The PAML documentation is very detailed and we have a PAML Wiki, plenty of tutorials and data examples that people can go through, and protocol papers with GitHub repositories that can be used to reproduce the steps detailed in such protocols -- I highly suggest you go through those! :)

**Comment by Tangbbmc** [comment]
@sabifo4 
[TWG_PAML_New_anlysis.zip](https://github.com/user-attachments/files/17691266/TWG_PAML_New_anlysis.zip)

Dear Sandra,
      I am sorry to disturb you again! I have read the article entitled Beginner’s Guide on the Use of PAML to Detect Positive Selection and the protocol in the GitHub repository (https:// github.com/abacus-gene/paml-tutorial/tree/main/positiveselection/. After that, I prepared the new input files and re-analyzed the positive selection of 20 bacterial protein-coding genes from the same genus using the branch-site model with PAML. The protein alignment-based codon alignment was generated with MAFFT version 7 and PAL2NAL, with removing the gaps. The sequence file in phylip format was obtained with sequence format convertor tool of EasyCodeML software. The ML tree was constructed with iqtree and viewed with FigTree. The branch lengths in the tree file were removed with the script in the GitHub repository. The tree was unrooted using the protocol you described in Supplementary data of the article mentioned-above. 
      We tested three different CodonFreq values (=2, 3, and 7) with branch-site model A (model = 0; NSsites = 0; fix_omega = 0; omega = 0.5), which revealed that the fully conserved Ser307 I mentioned previously was a positively selected site with high posterior probability value. For CodonFreq=2, five positively selected sites ( 8 L 0.667; 45 L 0.989*; 149 R 0.956*; 307 S 0.996**; 371 A 0.986*) were observed based on Bayes Empirical Bayes (BEB) analysis; for CodonFreq=3, eleven positively selected sites (8 L 0.767; 38 R 0.789; 45 L 0.971*; 46 S 0.607; 95 N 0.515; 149 R 0.992**; 307 S 0.998**; 321 E 0.902; 326 H 0.521; 371 A 0.999**; 426 T 0.963*) were found; for CodonFreq=7, only four positively selected sites (45 L 0.887; 149 R 0.927; 307 S 0.989*; 371 A 0.984*). All input and output files were provided as a compressed file. Here, I still fail to understand why a fully conserved residue (Ser307) in all lineages was identified as a positive selection site. Does it have similar reports? 
      In your last reply, you mentioned that when re-running our analyses, you found only 4 sites that are potentially under positive selection under the branch-site model, which are different from the sites our found except for the sites in position 45. When I re-run the previous data, similar results were found. The four sites under positive selection were 45L, 150R, 308S, and 372A, but based on the protein sequence alignment analysis, the latter three sites should be equivalent the residues 149R, 307S, and 371A, because in some lineages, the residue numbering may have small differences due to the insertion of gap (gaps were removed in the new analysis). For example, 308S in Ne protein is equivalent to 307S in Ng protein. Therefore, the 4 sites you found were included in the five sites we found. 
     I am looking forward to your reply as soon as possible!  
    Best regards

**Comment by Tangbbmc** [comment]
@sabifo4 Dear Sandra,
      Do you have time to read my previous reply mentioned above? Is it possible that a fully conserved residue can also be identified as a positively selected site?

**Comment by Tangbbmc** [comment]
@sabifo4 Dear Sandra,
      Do you have time to read my previous reply mentioned above? Is it possible that a fully conserved residue can also be identified as a positively selected site?

**Comment by sabifo4** [comment]
Apologies for my late reply, @Tangbbmc , I have been busy with other projects and did not see the repository notifications as this issue is closed.

A fully conserved residue can be identified as a positively selected site when the MLEs of parameters are extreme. For example, under the site model, you may get 100% for a site class with w > 1. The NEB calculation then will suggest that every site is under positive selection with w > 1. The BEB calculation may and may not do so. Nevertheless, please bear in mind that the results under NEB are discouraged to be used, and you should focus on those given by the BEB.

I know that you could not access the PAML discussion group but, in case you can find a way to do so (e.g., someone could post on your behalf), you would be able to benefit from the input of other users -- the PAML GitHub issues are aimed at troubleshooting technical issues, they are not intended for discussions on results interpretations :) 

Hope the details above can clarify your question!

All the best,
Sandy

**Comment by sabifo4** [comment]
P.S.: I deleted one of your comments as they were just a duplicate :)
